### ISSUE TITLE
OSS License?

### ISSUE THREAD

**Issue by richardszalay** [markeverard/POSSIBLE.TokenBasedAccess#1]
Hi there,

Any chance you can add an OSS license to the project (or at least confirm in this issue)? Technically you're not allowing anyone to use your code as there's no license attached.

(MIT / Apache 2.0 tends to be useful for "just do what you want with it", but read up before making a decision)

Cheers, 
Richard

**Comment by markeverard** [comment]
I've added a MIT license, so knock yourself out! 
Its been a while since I've looked at this, it will probably require a little rework if you are looking at using it for EPiServer 7+
Good luck!
